name: pharmo_app
description: "Эмийн бөөний худалда, захиалгын систем."
publish_to: none


version: 2.0.8+81
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  jwt_decoder: ^2.0.1
  badges: ^3.1.2
  qr_flutter: ^4.1.0
  geolocator: ^14.0.2
  url_launcher: ^6.2.6
  flutter_dotenv: ^6.0.0
  calendar_date_picker2: ^2.0.0
  firebase_messaging: ^16.0.2
  rflutter_alert: ^2.0.4
  firebase_core: ^4.1.1
  flutter_local_notifications: ^19.0.0
  device_info_plus: ^12.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  insta_image_viewer: ^1.0.4
  flutter_slidable:
    git:
      url: "https://github.com/letsar/flutter_slidable"
  otp_text_field_v2: ^1.0.3
  permission_handler: ^12.0.1
  get: ^4.6.6
  package_info_plus: ^8.1.1
  restart_app: ^1.3.2
  upgrader: ^12.1.0
  image_picker: ^1.1.2
  google_maps: ^8.1.1
  google_maps_flutter: ^2.10.0
  image: ^4.5.2
  local_auth: ^2.3.0
  location: ^8.0.0
  # shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  battery_plus: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13  
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons_2/
    - assets/stickers/
    - assets/fonts/
    - .env
  fonts:
     - family: Sf-Pro-Text
       fonts:
        - asset: assets/fonts/SF Pro Text/SF-Pro-Text-Regular.otf
          weight: 300
        - asset: assets/fonts/SF Pro Text/SF-Pro-Text-Bold.otf
          weight: 500
          
