name: pharmo_app
description: "Эмийн бөөний худалда, захиалгын систем."
version: 1.0.6+46
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  infinite_scroll_pagination: ^4.0.0
  carousel_slider: ^4.2.1
  jwt_decoder: ^2.0.1
  badges: ^3.1.2
  qr_flutter: ^4.1.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.6
  flutter_dotenv: ^5.1.0
  calendar_date_picker2: ^1.0.2
  firebase_messaging: ^15.1.3
  rflutter_alert: ^2.0.4
  firebase_core: ^3.6.0
  flutter_local_notifications: ^17.0.0
  device_info_plus: ^10.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  insta_image_viewer: ^1.0.4
  flutter_slidable: ^3.1.1
  flutter_sliding_toast: ^1.4.2
  otp_text_field_v2: ^1.0.3
  permission_handler: 11.3.1
  get: ^4.6.6
  package_info_plus: ^8.1.1
  shorebird_code_push: ^2.0.2
  restart_app: ^1.3.2
  upgrader: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/1024.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons_2/
    - assets/stickers/
    - assets/fonts/
    - .env
    - shorebird.yaml
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          style: normal
          weight: 700 
