name: pharmo_app
description: "Эмийн бөөний худалда, захиалгын систем."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  infinite_scroll_pagination: ^4.0.0
  carousel_slider: ^4.2.1
  jwt_decoder: ^2.0.1
  badges: ^3.1.2
  qr_flutter: ^4.1.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.6
  flutter_dotenv: ^5.1.0
  calendar_date_picker2: ^1.0.2
  firebase_messaging: ^14.9.2
  rflutter_alert: ^2.0.4
  firebase_core: ^2.31.0
  flutter_local_notifications: ^17.0.0
  device_info_plus: ^10.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  insta_image_viewer: ^1.0.4
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/1024.png"
  
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/icons_2/
    - .env
    # - images/no_image.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Lato-Regular
  #     fonts:
  #       - asset: assets/fonts/Lato-Regular.ttf
  #         style: normal
          
  #   - family: LilitaOneRegular
  #     fonts:
  #       - asset: assets/fonts/LilitaOneRegular.ttf
  #   - family: Lobster
  #     fonts:
  #       - asset: assets/fonts/Lobster.ttf
  #       - style: normal
  #   - family: PassionOneBold
  #     fonts:
  #       - asset: assets/fonts/PassionOneBold.ttf
  #       - style: normal


  # #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
