name: pharmo_app
description: "Эмийн бөөний худалда, захиалгын систем."

version: 1.0.12+56
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  carousel_slider: ^5.0.0
  jwt_decoder: ^2.0.1
  badges: ^3.1.2
  qr_flutter: ^4.1.0
  geolocator: ^13.0.2
  url_launcher: ^6.2.6
  flutter_dotenv: ^5.1.0
  calendar_date_picker2: ^1.0.2
  firebase_messaging: ^15.1.3
  rflutter_alert: ^2.0.4
  firebase_core: ^3.6.0
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  insta_image_viewer: ^1.0.4
  flutter_slidable:
    git:
      url: "https://github.com/letsar/flutter_slidable"
  otp_text_field_v2: ^1.0.3
  permission_handler: ^11.4.0
  get: ^4.6.6
  package_info_plus: ^8.1.1
  shorebird_code_push: ^2.0.2
  restart_app: ^1.3.2
  upgrader: ^11.3.1
  image_picker: ^1.1.2
  google_maps: ^8.1.1
  google_maps_flutter: ^2.10.0
  image: ^4.5.2
  local_auth: ^2.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/1024.png"

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/icons_2/
    - assets/stickers/
    - assets/fonts/
    - .env
    - shorebird.yaml
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          style: normal
          weight: 700 
